theme: jekyll-theme-modernist
title: Adam Hochberger's Portfolio
bookmark: Bookmark this page to follow along with updates to my projects

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rogue
